export const RESET_FORMS =  'RESET_FORMS'

// contact
export const SEND_CONTACT_EMAIL =  'SEND_CONTACT_EMAIL'
export const SEND_CONTACT_EMAIL_FAILED =  'SEND_CONTACT_EMAIL_FAILED'

//auth
export const SIGNUP = 'SIGNUP'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SIGNIN = 'SIGNIN'
export const SIGNIN_FAILED = 'SIGNIN_FAILED'
export const SIGNOUT = 'SIGNOUT'

//password forgot
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
export const FORGOT_PASSWORD_OTP = 'FORGOT_PASSWORD_OTP'
export const FORGOT_PASSWORD_OTP_FAILED = 'FORGOT_PASSWORD_OTP_FAILED'
export const FORGOT_PASSWORD_RESET = 'FORGOT_PASSWORD_RESET'
export const FORGOT_PASSWORD_RESET_FAILED = 'FORGOT_PASSWORD_RESET_FAILED'

//account
export const FETCH_ACCOUNT_DETAILS = 'FETCH_ACCOUNT_DETAILS'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED'

//users
export const FETCH_USERS = 'FETCH_USERS'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
export const FETCH_USER = 'FETCH_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const DELETE_USER = 'DELETE_USER'
export const RESTORE_USER = 'RESTORE_USER'
export const FETCH_USERS_BIN = 'FETCH_USERS_BIN'
export const FORCE_DELETE_USER = 'FORCE_DELETE_USERS'